# Introducting Pytorch
___
Author: Simon Thornewill von Essen

Date: 02/07/2018
___

In this notebook I'll be taking some quick notes into Pytorches basic functionality.

* I installed CUDA using the following [guide](https://www.youtube.com/watch?v=uIm3DMprk7M&t=640s).
* You can also install PyTorch using the instructions on the [home website](https://pytorch.org/).

# Tensors in Pytorch


In [1]:
# Import Library
import numpy as np
import torch

In [4]:
# Make random numbers within a tensor
x = torch.rand(3, 2, 3)
x

tensor([[[ 0.0332,  0.1967,  0.3432],
         [ 0.0103,  0.6497,  0.8194]],

        [[ 0.2869,  0.4825,  0.7549],
         [ 0.6744,  0.4039,  0.6299]],

        [[ 0.5631,  0.9148,  0.7475],
         [ 0.5735,  0.9068,  0.2141]]])

In [5]:
# Make a tensor with all ones
y = torch.ones(3, 2, 3)
y

tensor([[[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]],

        [[ 1.,  1.,  1.],
         [ 1.,  1.,  1.]]])

In [6]:
# Add the two tensors together
x+y

tensor([[[ 1.0332,  1.1967,  1.3432],
         [ 1.0103,  1.6497,  1.8194]],

        [[ 1.2869,  1.4825,  1.7549],
         [ 1.6744,  1.4039,  1.6299]],

        [[ 1.5631,  1.9148,  1.7475],
         [ 1.5735,  1.9068,  1.2141]]])

In [8]:
# Can also be done by
x.add(y) # Put this change inplace by using x.add_(y)

tensor([[[ 1.0332,  1.1967,  1.3432],
         [ 1.0103,  1.6497,  1.8194]],

        [[ 1.2869,  1.4825,  1.7549],
         [ 1.6744,  1.4039,  1.6299]],

        [[ 1.5631,  1.9148,  1.7475],
         [ 1.5735,  1.9068,  1.2141]]])

In [9]:
# See the size of a tensor by calling size
x.size()

torch.Size([3, 2, 3])

In [15]:
# Possible to index and slice
x[0, 0, 0]

tensor(1.00000e-02 *
       3.3218)

In [16]:
# Possible to resize by calling resize
x.resize(3,2,3)

C:\Users\SimonThornewill\Anaconda3\lib\site-packages\torch\tensor.py:255: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([[[ 0.0332,  0.1967,  0.3432],
         [ 0.0103,  0.6497,  0.8194]],

        [[ 0.2869,  0.4825,  0.7549],
         [ 0.6744,  0.4039,  0.6299]],

        [[ 0.5631,  0.9148,  0.7475],
         [ 0.5735,  0.9068,  0.2141]]])

# Numpy to Torch and *vice versa*

In [18]:
# Create random tensor
a = np.random.rand(3, 3, 3)
a

array([[[0.97033604, 0.50674193, 0.14767428],
        [0.39897096, 0.85528882, 0.80364931],
        [0.57189963, 0.99980971, 0.79800547]],

       [[0.3521948 , 0.75569838, 0.55938287],
        [0.06791237, 0.9287622 , 0.68073479],
        [0.43733377, 0.24590249, 0.18478989]],

       [[0.84364975, 0.09804201, 0.35874552],
        [0.56418681, 0.58625239, 0.82161333],
        [0.50789113, 0.39383691, 0.1936377 ]]])

In [20]:
# Convert to torch
b = torch.from_numpy(a)
b

tensor([[[ 0.9703,  0.5067,  0.1477],
         [ 0.3990,  0.8553,  0.8036],
         [ 0.5719,  0.9998,  0.7980]],

        [[ 0.3522,  0.7557,  0.5594],
         [ 0.0679,  0.9288,  0.6807],
         [ 0.4373,  0.2459,  0.1848]],

        [[ 0.8436,  0.0980,  0.3587],
         [ 0.5642,  0.5863,  0.8216],
         [ 0.5079,  0.3938,  0.1936]]], dtype=torch.float64)

In [21]:
# Convert back to numpy
b.numpy()

array([[[0.97033604, 0.50674193, 0.14767428],
        [0.39897096, 0.85528882, 0.80364931],
        [0.57189963, 0.99980971, 0.79800547]],

       [[0.3521948 , 0.75569838, 0.55938287],
        [0.06791237, 0.9287622 , 0.68073479],
        [0.43733377, 0.24590249, 0.18478989]],

       [[0.84364975, 0.09804201, 0.35874552],
        [0.56418681, 0.58625239, 0.82161333],
        [0.50789113, 0.39383691, 0.1936377 ]]])